# Ersetze XXX mit deinen Supabase-Credentials von https://supabase.com
# SUPABASE_URL findest du in Supabase Dashboard -> Settings -> API
# SUPABASE_KEY ist der "anon public key"

SUPABASE_URL = "https://molldwmftlizjepqhkts.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vbGxkd21mdGxpemplcHFoa3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODY5NTYsImV4cCI6MjA4NTM2Mjk1Nn0.KF0VqdJj9TPeC3Z5iKxTGDh5tTSS9BaXlvqwO8utOdw"
